analyzer:
  exclude:
    - lib/dataconnect_generated/**
  errors:
    prefer_single_quotes: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_single_quotes
    - sort_child_properties_last
    - avoid_print
